### ISSUE TITLE
Exception when local in Qualified Domain contains equal sign, unproper escape

### ISSUE THREAD

**Issue by ahmadzuhd** [lucmoreau/ProvToolbox#190]
I have a provenance generated from camflow (https://camflow.org/) ... the Qualified Domains for the identifiers for entities, activities and agents contain equal sign at the end... below is an example..
```
{
    "prefix":
    {
        "prov": "http://www.w3.org/ns/prov",
        "cf": "http://www.camflow.org"
    },
    "agent":
    {
        "cf:EAAAAAAAABQFFQAAAAAAACAAAAA+KXBJAQAAAAAAAAA=":
        {
            "cf:id": "5381",
            "prov:type": "machine",
            "cf:boot_id": 32,
            "cf:machine_id": "cf:1232087358",
            "cf:version": 1,
            "cf:date": "2022:04:05T23:03:51",
            "cf:taint": "0",
            "cf:jiffies": "0",
            "cf:epoch": 0,
            "cf:u_sysname": "Linux",
            "cf:u_nodename": "fedora-spade",
            "cf:u_release": "5.11.17-200.camflow.fc33.x86_64",
            "cf:u_version": "#1 SMP Thu Apr 29 05:05:58 UTC 2021",
            "cf:u_machine": "x86_64",
            "cf:u_domainname": "(none)",
            "cf:k_version": "0.7.2",
            "cf:l_version": "v0.5.3",
            "cf:l_commit": "2665c81d74ac55ae680792ae7a060fffa21028da"
        }
    }
}
```

I got exception when trying to read the file to a document when running "ProvToolbox Tutorial 2"

below is the exception i get:

`Exception in thread "main" org.openprovenance.prov.model.exception.QualifiedNameException: PROV-N QualifiedName: local name not valid EAAAAAAAABQFFQAAAAAAACAAAAA+KXBJAQAAAAAAAAA=
        at org.openprovenance.prov.xml.ProvFactory.newQualifiedName(ProvFactory.java:209)
        at org.openprovenance.prov.xml.ProvFactory.newQualifiedName(ProvFactory.java:196)
        at org.openprovenance.prov.model.Namespace.stringToQualifiedName(Namespace.java:248)
        at org.openprovenance.prov.json.ProvDocumentDeserializer.decodeStatement(ProvDocumentDeserializer.java:176)
        at org.openprovenance.prov.json.ProvDocumentDeserializer.decodeElements(ProvDocumentDeserializer.java:149)
        at org.openprovenance.prov.json.ProvDocumentDeserializer.decodeBundle(ProvDocumentDeserializer.java:126)        at org.openprovenance.prov.json.ProvDocumentDeserializer.deserialize(ProvDocumentDeserializer.java:91)  
        at org.openprovenance.prov.json.ProvDocumentDeserializer.deserialize(ProvDocumentDeserializer.java:60)  
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:59)
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:53)
        at com.google.gson.Gson.fromJson(Gson.java:755)
        at com.google.gson.Gson.fromJson(Gson.java:694)
        at org.openprovenance.prov.json.Converter.readDocument(Converter.java:44)
        at org.openprovenance.prov.interop.InteropFramework.readDocumentFromFile(InteropFramework.java:714)     
        at org.openprovenance.prov.interop.InteropFramework.readDocumentFromFile(InteropFramework.java:692)     
        at org.openprovenance.prov.tutorial.tutorial2.ReadWrite.doConversions(ReadWrite.java:42)
        at org.openprovenance.prov.tutorial.tutorial2.ReadWrite.main(ReadWrite.java:65)`

**Comment by lucmoreau** [comment]
According to PROV-N, Production [55] (See https://www.w3.org/TR/prov-n/#prod-PN_CHARS_ESC) states that = needs to be escaped in a local name.

So, the behaviour is correct.
