### ISSUE TITLE
Error when trying to serialize a document to json after using prov-nf on it

### ISSUE THREAD

**Issue by jurka14** [lucmoreau/ProvToolbox#216]
Hi,
I am building a tool for provenance generation, and the last step before outputting the document is converting it into a canonical form. Using the `prov-nf` module, I encountered a problem while trying to serialize the document to JSON format. All other formats that I tried have worked fine.

The code used:

```
org.openprovenance.prov.scala.immutable.Document nDoc = CommandLine$.MODULE$
                .parseDocumentToNormalForm(new FileInput(new File("test.provn"))).toDocument();

DocumentProxyFromStatements fDoc = Normalizer$.MODULE$.
        fusion(nDoc);

org.openprovenance.prov.model.Document canonizedDoc = new DocumentProxy(
        new NoIdStatementIndexer(fDoc.getStatements()),
        new StatementIndexer(),
        fDoc.getNamespace()
).toDocument();

intF.writeDocument("test.json", canonizedDoc);
```
Minimal reproducible example:
```
InteropFramework intF = new InteropFramework();

DocumentProxy nDoc = CommandLine$.MODULE$
        .parseDocumentToNormalForm(new FileInput(new File("test.provn")));

org.openprovenance.prov.model.Document canonizedDoc = nDoc.toDocument();

intF.writeDocument("test.json", canonizedDoc);
```
The output:
```
com.fasterxml.jackson.databind.JsonMappingException: class org.openprovenance.prov.scala.immutable.QualifiedName cannot be cast to class org.openprovenance.prov.vanilla.QualifiedName (org.openprovenance.prov.scala.immutable.QualifiedName and org.openprovenance.prov.vanilla.QualifiedName are in unnamed module of loader 'app') (through reference chain: org.openprovenance.prov.core.json.serialization.SortedDocument["entity"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3923)
	at org.openprovenance.prov.core.json.serialization.ProvSerialiser.serialiseDocument(ProvSerialiser.java:52)
	at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:157)
	at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:120)
	at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:133)
	at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:57)
	at org.openprovenance.prov.interop.InteropFramework.writeDocument(InteropFramework.java:728)
	at cpm.Demo.main(Demo.java:84)
Caused by: java.lang.ClassCastException: class org.openprovenance.prov.scala.immutable.QualifiedName cannot be cast to class org.openprovenance.prov.vanilla.QualifiedName (org.openprovenance.prov.scala.immutable.QualifiedName and org.openprovenance.prov.vanilla.QualifiedName are in unnamed module of loader 'app')
	at org.openprovenance.prov.core.json.serialization.serial.CustomQualifiedNameSerializerAsField.serialize(CustomQualifiedNameSerializerAsField.java:11)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(MapSerializer.java:897)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:762)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	... 12 more
Exception in thread "main" org.openprovenance.prov.model.exception.UncheckedException: Unchecked Exception
	at org.openprovenance.prov.core.json.serialization.ProvSerialiser.serialiseDocument(ProvSerialiser.java:58)
	at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:157)
	at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:120)
	at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:133)
	at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:57)
	at org.openprovenance.prov.interop.InteropFramework.writeDocument(InteropFramework.java:728)
	at cpm.Demo.main(Demo.java:84)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: class org.openprovenance.prov.scala.immutable.QualifiedName cannot be cast to class org.openprovenance.prov.vanilla.QualifiedName (org.openprovenance.prov.scala.immutable.QualifiedName and org.openprovenance.prov.vanilla.QualifiedName are in unnamed module of loader 'app') (through reference chain: org.openprovenance.prov.core.json.serialization.SortedDocument["entity"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3923)
	at org.openprovenance.prov.core.json.serialization.ProvSerialiser.serialiseDocument(ProvSerialiser.java:52)
	... 6 more
Caused by: java.lang.ClassCastException: class org.openprovenance.prov.scala.immutable.QualifiedName cannot be cast to class org.openprovenance.prov.vanilla.QualifiedName (org.openprovenance.prov.scala.immutable.QualifiedName and org.openprovenance.prov.vanilla.QualifiedName are in unnamed module of loader 'app')
	at org.openprovenance.prov.core.json.serialization.serial.CustomQualifiedNameSerializerAsField.serialize(CustomQualifiedNameSerializerAsField.java:11)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(MapSerializer.java:897)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:762)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	... 12 more

Process finished with exit code 1

```

**Comment by lucmoreau** [comment]
provn and jsonld are the only format natively supported for the scala representation.

The json format is not supported for the scala representation (as we see it as a legacy format). Hopefully the jsonld  representation should be working and should be suitable for you.

The test in the scala package convert the scala representation to java before serialisation.  To do this, see the following 2 lines:
https://github.com/lucmoreau/ProvToolbox/blob/7c73074439cd831a136320eded56193522c59490/modules-core/prov-model-scala/src/test/java/org/openprovenance/prov/scala/model/immutable/RoundTripJavaToScalaBackToJavaTest.java#L32-L33

--
Professor Luc Moreau,  Head of Department
Department of Informatics, King’s College London
Strand Campus, Bush House, 30 Aldwych, London, WC2B 4BG.
Tel: +44 207 848 6808, web: https://nms.kcl.ac.uk/luc.moreau/



From: Vojtěch Jurka ***@***.***>
Date: Wednesday, 1 May 2024 at 10:36
To: lucmoreau/ProvToolbox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lucmoreau/ProvToolbox] Error when trying to serialize a document to json after using prov-nf on it (Issue #216)

Hi,
I am building a tool for provenance generation, and the last step before outputting the document is converting it into a canonical form. Using the prov-nf module, I encountered a problem while trying to serialize the document to JSON format. All other formats that I tried have worked fine.

The code used:

org.openprovenance.prov.scala.immutable.Document nDoc = CommandLine$.MODULE$

                .parseDocumentToNormalForm(new FileInput(new File("test.provn"))).toDocument();



DocumentProxyFromStatements fDoc = Normalizer$.MODULE$.

        fusion(nDoc);



org.openprovenance.prov.model.Document canonizedDoc = new DocumentProxy(

        new NoIdStatementIndexer(fDoc.getStatements()),

        new StatementIndexer(),

        fDoc.getNamespace()

).toDocument();



intF.writeDocument("test.json", canonizedDoc);

Minimal reproducible example:

InteropFramework intF = new InteropFramework();



DocumentProxy nDoc = CommandLine$.MODULE$

        .parseDocumentToNormalForm(new FileInput(new File("test.provn")));



org.openprovenance.prov.model.Document canonizedDoc = nDoc.toDocument();



intF.writeDocument("test.json", canonizedDoc);

The output:

com.fasterxml.jackson.databind.JsonMappingException: class org.openprovenance.prov.scala.immutable.QualifiedName cannot be cast to class org.openprovenance.prov.vanilla.QualifiedName (org.openprovenance.prov.scala.immutable.QualifiedName and org.openprovenance.prov.vanilla.QualifiedName are in unnamed module of loader 'app') (through reference chain: org.openprovenance.prov.core.json.serialization.SortedDocument["entity"])

        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)

        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)

        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)

        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780)

        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)

        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)

        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)

        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)

        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3923)

        at org.openprovenance.prov.core.json.serialization.ProvSerialiser.serialiseDocument(ProvSerialiser.java:52)

        at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:157)

        at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:120)

        at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:133)

        at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:57)

        at org.openprovenance.prov.interop.InteropFramework.writeDocument(InteropFramework.java:728)

        at cpm.Demo.main(Demo.java:84)

Caused by: java.lang.ClassCastException: class org.openprovenance.prov.scala.immutable.QualifiedName cannot be cast to class org.openprovenance.prov.vanilla.QualifiedName (org.openprovenance.prov.scala.immutable.QualifiedName and org.openprovenance.prov.vanilla.QualifiedName are in unnamed module of loader 'app')

        at org.openprovenance.prov.core.json.serialization.serial.CustomQualifiedNameSerializerAsField.serialize(CustomQualifiedNameSerializerAsField.java:11)

        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(MapSerializer.java:897)

        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:762)

        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)

        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)

        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)

        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)

        ... 12 more

Exception in thread "main" org.openprovenance.prov.model.exception.UncheckedException: Unchecked Exception

        at org.openprovenance.prov.core.json.serialization.ProvSerialiser.serialiseDocument(ProvSerialiser.java:58)

        at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:157)

        at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:120)

        at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:133)

        at org.openprovenance.prov.interop.Outputer.writeDocument(Outputer.java:57)

        at org.openprovenance.prov.interop.InteropFramework.writeDocument(InteropFramework.java:728)

        at cpm.Demo.main(Demo.java:84)

Caused by: com.fasterxml.jackson.databind.JsonMappingException: class org.openprovenance.prov.scala.immutable.QualifiedName cannot be cast to class org.openprovenance.prov.vanilla.QualifiedName (org.openprovenance.prov.scala.immutable.QualifiedName and org.openprovenance.prov.vanilla.QualifiedName are in unnamed module of loader 'app') (through reference chain: org.openprovenance.prov.core.json.serialization.SortedDocument["entity"])

        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)

        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)

        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)

        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780)

        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)

        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)

        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)

        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)

        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3923)

        at org.openprovenance.prov.core.json.serialization.ProvSerialiser.serialiseDocument(ProvSerialiser.java:52)

        ... 6 more

Caused by: java.lang.ClassCastException: class org.openprovenance.prov.scala.immutable.QualifiedName cannot be cast to class org.openprovenance.prov.vanilla.QualifiedName (org.openprovenance.prov.scala.immutable.QualifiedName and org.openprovenance.prov.vanilla.QualifiedName are in unnamed module of loader 'app')

        at org.openprovenance.prov.core.json.serialization.serial.CustomQualifiedNameSerializerAsField.serialize(CustomQualifiedNameSerializerAsField.java:11)

        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(MapSerializer.java:897)

        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:762)

        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)

        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)

        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)

        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)

        ... 12 more



Process finished with exit code 1
